name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build the Docker image
        run: |
          docker build . -t ghcr.io/sinkaroid/jandapress:${{ steps.tags.outputs.name }}
      - name: Push the Docker image
        run: |
          docker push ghcr.io/sinkaroid/jandapress:${{ steps.tags.outputs.name }}

