name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/sinkaroid/jandapress:latest
      - name: Push the Docker image
        run: docker push ghcr.io/sinkaroid/jandapress:latest

